DROP TABLE visit CASCADE;
DROP TABLE patient CASCADE;
DROP TABLE services CASCADE;
DROP TABLE doctor CASCADE;
DROP TABLE speciality CASCADE;
DROP SEQUENCE seq_doc CASCADE;
DROP SEQUENCE seq_patient_1 CASCADE;
DROP SEQUENCE seq_patient_2 CASCADE;
DROP SEQUENCE seq_spec CASCADE;
DROP SEQUENCE seq_srv CASCADE;
DROP SEQUENCE seq_visit CASCADE;

CREATE TABLE speciality (
    Code_Spec INTEGER NOT NULL,
    Tittle    VARCHAR(64) NOT NULL
);

ALTER TABLE speciality
ADD CONSTRAINT pk_Code_Spec PRIMARY KEY (Code_Spec);

CREATE SEQUENCE seq_spec
  START WITH 1401
  MAXVALUE 1755;

CREATE TABLE doctor (
    ID_Doctor INTEGER NOT NULL,
    Surname   VARCHAR(64) NOT NULL,
    Name      VARCHAR(64) NOT NULL,
    Middle_Name  VARCHAR(64),
    Code_Spec_Number INTEGER NOT NULL
);

ALTER TABLE doctor
ADD CONSTRAINT pk_ID_Doctor PRIMARY KEY (ID_Doctor);

ALTER TABLE doctor
ADD CONSTRAINT Spec_Doctor FOREIGN KEY (Code_Spec_Number) REFERENCES speciality (Code_Spec);

CREATE SEQUENCE  seq_doc
  START WITH 11 CACHE 20
  MINVALUE 1
  MAXVALUE 999
  INCREMENT BY 1;

CREATE TABLE patient (
    N_Card       INTEGER NOT NULL CHECK (N_Card >= 100000 AND N_Card <= 999999),
    Surname      VARCHAR(64) NOT NULL,
    Name         VARCHAR(64) NOT NULL,
    Middle_Name  VARCHAR(64) NOT NULL,
    Address 	 VARCHAR(128),
    Phone 	     VARCHAR(64) NOT NULL CHECK (LENGTH(PHONE) IN (13))
);

ALTER TABLE patient
ADD  CONSTRAINT pk_patient PRIMARY KEY (N_Card);

CREATE SEQUENCE seq_patient_1
  START WITH 116001
  MAXVALUE 116999
  INCREMENT BY 1;

CREATE SEQUENCE seq_patient_2
  START WITH 216001
  MAXVALUE 216999
  INCREMENT BY 1;

CREATE TABLE services (
    Code_Srv INTEGER NOT NULL,
    Tittle   VARCHAR(64) NOT NULL,
    Price    NUMERIC(8,2) NOT NULL CHECK (Price <= 1000)
);

ALTER TABLE services
ADD CONSTRAINT pk_Code_Srv PRIMARY KEY (Code_Srv);

CREATE SEQUENCE seq_srv
  START WITH 110
  MAXVALUE 990
  INCREMENT BY 10;


CREATE TABLE visit (
    N_Visit    INTEGER NOT NULL,
    ID_Doctor  INTEGER,
    ID_Patient INTEGER,
    Date_Visit DATE NOT NULL CHECK (Date_Visit
        BETWEEN TO_DATE('01.01.2022', 'DD.MM.YYYY') AND TO_DATE('31.12.2022', 'DD.MM.YYYY')),
    Code_Srv   INTEGER NOT NULL
);

ALTER TABLE visit
ADD CONSTRAINT pk_N_Visit PRIMARY KEY (N_Visit);

ALTER TABLE visit
ADD CONSTRAINT fk_ID_Doctor FOREIGN KEY (ID_Doctor) REFERENCES doctor (ID_Doctor);

ALTER TABLE visit
ADD CONSTRAINT fk_ID_Patient FOREIGN KEY (ID_Patient) REFERENCES patient (N_Card);

ALTER TABLE visit
ADD CONSTRAINT fk_Srv_Visit FOREIGN KEY (Code_Srv) REFERENCES services (Code_Srv);

CREATE SEQUENCE  seq_visit
  MINVALUE 1
  INCREMENT BY 1 CACHE 20;
