//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by App32.rc
//
#define IDD_APISHELL                    103
#define IDI_STATE1                      105
#define IDI_STATE2                      106
#define IDC_STATE1                      1009
#define IDC_STATE2                      1010
#define IDHIDE                          1019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         106
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
