//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by APIWin.rc
//
#define IDM_NEW                         100
#define IDM_OPEN                        101
#define IDM_SAVE                        102
#define IDM_SAVEAS                      103
#define IDM_EXIT                        104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
