--1
CREATE VIEW RETIREE AS
	SELECT *
		FROM EMP
			WHERE (MONTHS_BETWEEN(SYSDATE, BIRTHDATE) / 12) >= 60;

--2
CREATE VIEW FIREDS AS
	SELECT EMPNAME, ENDDATE, DEPTNAME, JOBNAME
		FROM EMP
		NATURAL JOIN CAREER
		NATURAL JOIN JOB
		NATURAL JOIN DEPT
			WHERE ENDDATE IS NOT NULL;

--3
CREATE VIEW Sotrudnik_3_kv AS
	SELECT e.EMPNAME AS Sotrudnik, j.JOBNAME AS Dolzhnost, SUM(s.SALVALUE) AS Itogo_3_kv
		FROM EMP e
		NATURAL JOIN JOB j
		NATURAL JOIN CAREER c
		NATURAL JOIN SALARY s
			WHERE s.YEAR = 2010 AND s.MONTH BETWEEN 7 AND 9
			AND c.ENDDATE IS NOT NULL
		GROUP BY E.EMPNAME, J.JOBNAME;

--4
CREATE VIEW FIREDS_2 AS
	SELECT EMPNAME, ENDDATE, DEPTNAME, JOBNAME, (MONTH || ', ' || SALVALUE) AS MONTH_TO_SUM
		FROM FIREDS
		NATURAL JOIN SALARY
			WHERE EMPNO in (SELECT EMPNO 
                		FROM FIREDS 
                		NATURAL JOIN SALARY 
                		GROUP BY EMPNO
                		HAVING COUNT(*)>2)

UPDATE RETIREE
		SET BIRTHDATE = SYSDATE
			WHERE EMPNAME = 'WARD';

INSERT INTO RETIREE 
	VALUES (7147, 'Test', TO_DATE('1940/05/03', 'yyyy/mm/dd'),7789)